[build]
  command = "npm run build"
  publish = "/"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
